-- SCHEMA (use dbo por padrão)
-- Se quiser isolar, crie: CREATE SCHEMA nextpark AUTHORIZATION dbo;

-- TABELAS
CREATE TABLE dbo.USUARIOS (
  ID        BIGINT IDENTITY(1,1) PRIMARY KEY,
  USERNAME  VARCHAR(80)  NOT NULL UNIQUE,
  [PASSWORD] VARCHAR(200) NOT NULL,
  [ROLE]    VARCHAR(20)  NOT NULL,
  CONSTRAINT CK_USUARIOS_ROLE CHECK ([ROLE] IN ('CLIENTE','GERENTE'))
);

CREATE TABLE dbo.VAGAS (
  ID      BIGINT IDENTITY(1,1) PRIMARY KEY,
  CODIGO  VARCHAR(20)  NOT NULL UNIQUE,
  [STATUS] VARCHAR(10) NOT NULL,
  CONSTRAINT CK_VAGAS_STATUS CHECK ([STATUS] IN ('LIVRE','OCUPADA'))
);

CREATE TABLE dbo.MOTOS (
  ID            BIGINT IDENTITY(1,1) PRIMARY KEY,
  PLACA         VARCHAR(10) NOT NULL UNIQUE,
  MODELO        VARCHAR(80) NOT NULL,
  [STATUS]      VARCHAR(15) NOT NULL,
  OWNER_USER_ID BIGINT      NOT NULL,
  VAGA_ID       BIGINT      NULL,
  CONSTRAINT CK_MOTOS_STATUS CHECK ([STATUS] IN ('ALOCADA','MANUTENCAO','VISTORIA','DESALOCADA')),
  CONSTRAINT FK_MOTOS_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES dbo.USUARIOS(ID),
  CONSTRAINT FK_MOTOS_VAGA  FOREIGN KEY (VAGA_ID)       REFERENCES dbo.VAGAS(ID)
);

CREATE TABLE dbo.HIST_MOV (
  ID              BIGINT IDENTITY(1,1) PRIMARY KEY,
  MOTO_ID         BIGINT      NOT NULL,
  ORIGEM_VAGA_ID  BIGINT      NULL,
  DESTINO_VAGA_ID BIGINT      NULL,
  ACAO            VARCHAR(20) NOT NULL,
  USUARIO         VARCHAR(80) NOT NULL,
  CREATED_AT      DATETIME2(6) NOT NULL CONSTRAINT DF_HIST_MOV_CREATED_AT DEFAULT SYSDATETIME(),
  CONSTRAINT FK_HIST_MOTO   FOREIGN KEY (MOTO_ID)         REFERENCES dbo.MOTOS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_HIST_ORIGEM FOREIGN KEY (ORIGEM_VAGA_ID)  REFERENCES dbo.VAGAS(ID),
  CONSTRAINT FK_HIST_DEST   FOREIGN KEY (DESTINO_VAGA_ID) REFERENCES dbo.VAGAS(ID)
);

-- ÍNDICES
CREATE INDEX IDX_MOTOS_OWNER   ON dbo.MOTOS (OWNER_USER_ID);
CREATE INDEX IDX_HIST_MOTO     ON dbo.HIST_MOV (MOTO_ID);
CREATE INDEX IDX_HIST_ORIGEM   ON dbo.HIST_MOV (ORIGEM_VAGA_ID);
CREATE INDEX IDX_HIST_DEST     ON dbo.HIST_MOV (DESTINO_VAGA_ID);
