-- SEQUENCES
CREATE SEQUENCE USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE VAGAS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MOTOS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HIST_MOV_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- TABELAS
CREATE TABLE USUARIOS (
  ID       NUMBER(19)     PRIMARY KEY,
  USERNAME VARCHAR2(80)   NOT NULL UNIQUE,
  PASSWORD VARCHAR2(200)  NOT NULL,
  ROLE     VARCHAR2(20)   NOT NULL CHECK (ROLE IN ('CLIENTE','GERENTE'))
);

CREATE TABLE VAGAS (
  ID     NUMBER(19)     PRIMARY KEY,
  CODIGO VARCHAR2(20)   NOT NULL UNIQUE,
  STATUS VARCHAR2(10)   NOT NULL CHECK (STATUS IN ('LIVRE','OCUPADA'))
);

CREATE TABLE MOTOS (
  ID            NUMBER(19)    PRIMARY KEY,
  PLACA         VARCHAR2(10)  NOT NULL UNIQUE,
  MODELO        VARCHAR2(80)  NOT NULL,
  STATUS        VARCHAR2(15)  NOT NULL CHECK (STATUS IN ('ALOCADA','MANUTENCAO','VISTORIA','DESALOCADA')),
  OWNER_USER_ID NUMBER(19)    NOT NULL,
  VAGA_ID       NUMBER(19),
  CONSTRAINT FK_MOTOS_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_MOTOS_VAGA  FOREIGN KEY (VAGA_ID)       REFERENCES VAGAS(ID)
);

CREATE TABLE HIST_MOV (
  ID              NUMBER(19)   PRIMARY KEY,
  MOTO_ID         NUMBER(19)   NOT NULL,
  ORIGEM_VAGA_ID  NUMBER(19),
  DESTINO_VAGA_ID NUMBER(19),
  ACAO            VARCHAR2(20) NOT NULL,
  USUARIO         VARCHAR2(80) NOT NULL,
  CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_HIST_MOTO   FOREIGN KEY (MOTO_ID)         REFERENCES MOTOS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_HIST_ORIGEM FOREIGN KEY (ORIGEM_VAGA_ID)  REFERENCES VAGAS(ID),
  CONSTRAINT FK_HIST_DEST   FOREIGN KEY (DESTINO_VAGA_ID) REFERENCES VAGAS(ID)
);
