INSERT INTO VAGAS (ID, CODIGO, STATUS) VALUES (VAGAS_SEQ.NEXTVAL, 'A01', 'LIVRE');
INSERT INTO VAGAS (ID, CODIGO, STATUS) VALUES (VAGAS_SEQ.NEXTVAL, 'A02', 'LIVRE');
INSERT INTO VAGAS (ID, CODIGO, STATUS) VALUES (VAGAS_SEQ.NEXTVAL, 'B01', 'LIVRE');
